## CLASE: MiembroArmadura()

In [17]:
#############
# Librerias #
#############

import math
import numpy as np

#########
# Clase #
#########

class MiembroArmadura():
    '''  
    Descripción:
    Esta clase sirve para obtener las propiedades de cualquier elemento de una armadura.
    
    Funciones:
    --> Longitud(self)
    --> Rig_Loc(self)
    --> def Lambda_X(self)
    --> def Lambda_Y(self)
    --> def Trans(self)
    --> def Rig_Glob(self)
    
    Programó:
    M. en I. Josue Emmanuel Cruz Barragan
    '''
    def __init__(self, elemento, area, modElasticidad, coordenada_xi, coordenada_yi, coordenada_xf, coordenada_yf, vec_coord):
        
        ####################
        # Datos de entrada #
        ####################
        
        self.elem = elemento
        self.A = area
        self.E = modElasticidad
        self.xi = coordenada_xi
        self.yi = coordenada_yi
        self.xf = coordenada_xf
        self.yf = coordenada_yf
        self.vc = vec_coord
        
        ###############
        # Propiedades #
        ###############
        
        self.L = self.Longitud()
        self.k_loc = self.Rig_Loc()
        self.lx = self.Lambda_X()
        self.ly = self.Lambda_Y()
        self.T = self.Trans()
        self.k_glob = self.Rig_Glob()
        
        #######################################################
        # Funciones para obtener las propiedades del elemento #
        #######################################################
        
    def __str__(self):
        print("Area: ", self.A)
        print("Mod. Elasticidad: ", self.E)
        print("Coordenadas Iniciales: ({} , {})".format(self.xi, self.yi))
        print("Coordenadas Finales: ({} , {})".format(self.xf, self.yf))
        print("Vector de Cooredenadas: ", self.vc)
        print("Longitud: ", self.L)
        print("Rigidez Local:", self.k_loc)
        print("Lx = ", self.lx,"  Ly = ", self.ly )
        print("Matriz de Transformacion: ", self.T)
        print("")
        print("Rigidez global del elemento:", self.k_glob)
        return ""
    
    def Longitud(self):
        """Calcula la longitud del elemento."""
        return math.sqrt((self.xf-self.xi)**2 + (self.yf-self.yi)**2)
    
    def Rig_Loc(self):
        """Calcula la matriz de rigidez local del elemento."""
        return (self.A*self.E/self.L) * np.array([[1,-1],[-1,1]])
    
    def Lambda_X(self):
        """Calcula la lambda X del elemento."""
        return (self.xf-self.xi)/self.L
    
    def Lambda_Y(self):
        """Calcula la lambda Y del elemento."""
        return (self.yf-self.yi)/self.L
    
    def Trans(self):
        """Calcula la matriz de tarnsformación del elemento."""
        return np.array([[self.lx, self.ly, 0, 0],[0, 0, self.lx, self.ly]])
    
    def Rig_Glob(self):
        """Calcula la matriz de rigidez global del elemento."""
        Tt = np.transpose(self.T)
        Tt_k_loc = np.matmul(Tt,self.k_loc)
        return np.matmul(Tt_k_loc,self.T)


# CAPÍTULO 3.

## TABLAS QUE SE USARÁN COMO DATOS DE ENTRADA EN LA NUEVA CLASE.

### Tabla de Elementos y Nodos:

<img src="Img/elem_nod.png">

### Tabla de Fuerzas y Desplazamientos:

<img src="Img/fuerza_desp.png">

## CLASE: AnalisisMatrcial.

<img src="Img/ClaseAnalisisMatricial.png">

## FUNCIONES QUE SE PROGRAMARÁN EN EL CODIGO:

<img src="Img/vectorcoordenadasglobales.png">

<img src="Img/matrizPI.png">

<img src="Img/Armadura.png">

<img src="Img/matrizrigidezglobal.png">

## CÓDIGO.

In [18]:
#########
# Clase #
#########

class AnalisisMatricial():
    '''  
    Descripción:
    Esta clase sirve para resolver cualquier armadura en 2D, tanto isostatica como hiperestatica. Tambien nos permite acceder 
    a las propiedades de cuaquiera de sus elementos y a las reacciones, desplazamientos, fuerzas internas, etc.
    
    Funciones:
    --> VectorCoordenadasGlobales(self)
    --> Matriz_PI(self)
    --> Armadura(self)
    --> MatrizRigidezGlobal(self)
    --> y más ...
    
    Programó:
    M. en I. Josue Emmanuel Cruz Barragan
    '''
    def __init__(self, tbl_Elem, tbl_Nods, tbl_Frza, tbl_Desp):
        
        ####################
        # Datos de entrada #
        ####################
        
        self.tE = tbl_Elem # Tabla de elementos.
        self.tN = tbl_Nods # Tabla de nodos.
        self.tF = tbl_Frza # Tabla de fuerzas.
        self.tD = tbl_Desp # Tabla de desplazamientos.
        
        ###############
        # Propiedades #
        ###############
        
        self.nE = len(self.tE) # Número de elementos en la estructura.
        self.nN = len(self.tN) # Número de nodos en la estructura.
        self.nGl = self.nN*2 # Número de grados de libertad en la estructura.
        # [Número de reacciones, Número de fuerzas conocidas, Diccionario de nodos]
        [self.nR, self.nFc, self.N] = self.VectorCoordenadasGlobales()
        self.PI = np.array(self.Matriz_PI()) # Matriz PI.
        self.Armad = self.Armadura() # Lista de las propiedades de los elementos.
        self.Kg = self.MatrizRigidezGlobal() # Matriz de rigidez global del elemento.
        
        
        #########################
        # Funciones de la clase #
        #########################
        
    def __str__(self):
        print("Numero de Elementos: ", self.nE)
        print("Numero de Nodos: ", self.nN)
        print("Numero de Grados de Libertad: ", self.nGl)
        print("Numero de Reacciones: ", self.nR)
        print("Numero de Fuerzas Conocidas: ", self.nFc)
        print("Diccionario de Nodos: ", self.N)
        print("\n Matriz PI: \n", self.PI)
        print("\n Elemento 3: \n", self.Armad[2])
        print("\n Matriz de Rigidez Global de la Armadura: \n", self.Kg)
        return ""
    
    def VectorCoordenadasGlobales(self):
        """Calcula el número de reacciones, número de fuerzas conocidas y un diccionario de nodos."""
        numReacciones = 0
        DiccionarioNodos = {}
        c = 1
        gl = self.nGl
        
        for i in range(self.nN):
            tipo = self.tN[i][3]
            
            NODO_key = self.tN[i][0]
            cx = self.tN[i][1]
            cy = self.tN[i][2]
            
            
            if tipo == "Libre":
                numReacciones += 0
                DiccionarioNodos.setdefault(NODO_key, [cx, cy, c, c+1])
                c+=2
                
            elif tipo == "Fijo":
                numReacciones += 2
                DiccionarioNodos.setdefault(NODO_key, [cx, cy, gl-1, gl])
                gl-=2
            
            elif tipo == "DX":
                numReacciones += 1
                DiccionarioNodos.setdefault(NODO_key, [cx, cy])
            
            elif tipo == "DY":
                numReacciones += 1
                DiccionarioNodos.setdefault(NODO_key, [cx, cy])
                
        numFuerzasConocidas = self.nGl - numReacciones  
        return numReacciones, numFuerzasConocidas, DiccionarioNodos
    
    def Matriz_PI(self):
        """Calcula la matriz de permutación PI."""
        PI = []
        for i in range(self.nE):
            ni = self.tE[i][3]
            nf = self.tE[i][4]
            PI.append([self.N[ni][2],self.N[ni][3],self.N[nf][2],self.N[nf][3]])
        return PI
    
    def Armadura(self):
        """Calcula la lista de propiedades de cada elemento de la armadura."""
        Elem = []
        for i in range(self.nE):
            el = self.tE[i][0]
            a = self.tE[i][1]
            me = self.tE[i][2]
            NI = self.tE[i][3]
            NF = self.tE[i][4]
            xi = self.N[NI][0]
            yi = self.N[NI][1]
            xf = self.N[NF][0]
            yf = self.N[NF][1]
            clix = self.N[NI][2]
            cliy = self.N[NI][3]
            clfx = self.N[NF][2]
            clfy = self.N[NF][3]
            Elem.append(MiembroArmadura(el, a, me, xi, yi, xf, yf, [clix, cliy, clfx, clfy]))
        return Elem
    
    def MatrizRigidezGlobal(self):
        """Calcula la matriz de rigidez global de la armadura."""
        K = np.zeros((self.nGl, self.nGl))
        for e in range(self.nE):
            ke_global = self.Armad[e].k_glob
            for i in range(4):
                for j in range(4):
                    a = self.PI[e,i]-1
                    b = self.PI[e,j]-1
                    K[a,b] = ke_global[i,j] + K[a,b]
        return K

## EJEMPLO.

<img src="Img/Ejemplo.png">

In [19]:
A = 2 # Área en, m2
E = 1800 # Modulo de Elasticidad en, kgf/m2

# Tabla de Elementos:
tbl_Elem = [
    ['E1', A, E, 'N5', 'N1'],
    ['E2', A, E, 'N2', 'N1'],
    ['E3', A, E, 'N3', 'N2'],
    ['E4', A, E, 'N2', 'N5'],
    ['E5', A, E, 'N3', 'N5'],
    ['E6', A, E, 'N4', 'N5'],
    ['E7', A, E, 'N4', 'N3']]
     
# Tabla de Nodos:
tbl_Nods = [
    ['N1', 14, 7, "Libre"],
    ['N2', 7, 7, "Libre"],
    ['N3', 0, 7, "Fijo"],
    ['N4', 0, 0, "Fijo"],
    ['N5', 7, 0, "Libre"]]

# Tabla de Fuerzas:
tbl_Frza = [
    [ -3, 'N2', 'DY'],
    [ -2, 'N1', 'DY']]

# Tabla de Desplazamientos:
tbl_Desp = [
    [ 0, 'N3', 'DX'],
    [ 0, 'N3', 'DY'],
    [ 0, 'N4', 'DX'],
    [ 0, 'N4', 'DY']]

AE = AnalisisMatricial(tbl_Elem, tbl_Nods, tbl_Frza, tbl_Desp)
print(AE)

Numero de Elementos:  7
Numero de Nodos:  5
Numero de Grados de Libertad:  10
Numero de Reacciones:  4
Numero de Fuerzas Conocidas:  6
Diccionario de Nodos:  {'N1': [14, 7, 1, 2], 'N2': [7, 7, 3, 4], 'N3': [0, 7, 9, 10], 'N4': [0, 0, 7, 8], 'N5': [7, 0, 5, 6]}

 Matriz PI: 
 [[ 5  6  1  2]
 [ 3  4  1  2]
 [ 9 10  3  4]
 [ 3  4  5  6]
 [ 9 10  5  6]
 [ 7  8  5  6]
 [ 7  8  9 10]]

 Elemento 3: 
 Area:  2
Mod. Elasticidad:  1800
Coordenadas Iniciales: (0 , 7)
Coordenadas Finales: (7 , 7)
Vector de Cooredenadas:  [9, 10, 3, 4]
Longitud:  7.0
Rigidez Local: [[ 514.28571429 -514.28571429]
 [-514.28571429  514.28571429]]
Lx =  1.0   Ly =  0.0
Matriz de Transformacion:  [[1. 0. 0. 0.]
 [0. 0. 1. 0.]]

Rigidez global del elemento: [[ 514.28571429    0.         -514.28571429    0.        ]
 [   0.            0.            0.            0.        ]
 [-514.28571429    0.          514.28571429    0.        ]
 [   0.            0.            0.            0.        ]]


 Matriz de Rigidez Global de