# CAPÍTULO 2.

## DATOS DEL ELEMENTO.

<img src="Img/datos.png">

## PROPIEDADES DEL ELEMENTO.

<img src="Img/propiedades.png">

## FÓRMULAS PARA LA CLASE: MiembroArmadura().

<img src="Img/formulas.png">

## CÓDIGO

In [10]:
#############
# Librerias #
#############

import math
import numpy as np

#########
# Clase #
#########

class MiembroArmadura():
    '''  
    Descripción:
    Esta clase sirve para obtener las propiedades de cualquier elemento de una armadura.
    
    Funciones:
    --> Longitud(self)
    --> Rig_Loc(self)
    --> def Lambda_X(self)
    --> def Lambda_Y(self)
    --> def Trans(self)
    --> def Rig_Glob(self)
    
    Programó:
    Ing. Josue Emmanuel Cruz Barragan
    '''
    def __init__(self, elemento, area, modElasticidad, coordenada_xi, coordenada_yi, coordenada_xf, coordenada_yf, vec_coord):
        
        ####################
        # Datos de entrada #
        ####################
        
        self.elem = elemento
        self.A = area
        self.E = modElasticidad
        self.xi = coordenada_xi
        self.yi = coordenada_yi
        self.xf = coordenada_xf
        self.yf = coordenada_yf
        self.vc = vec_coord
        
        ###############
        # Propiedades #
        ###############
        
        self.L = self.Longitud()
        self.k_loc = self.Rig_Loc()
        self.lx = self.Lambda_X()
        self.ly = self.Lambda_Y()
        self.T = self.Trans()
        self.k_glob = self.Rig_Glob()
        
        #######################################################
        # Funciones para obtener las propiedades del elemento #
        #######################################################
        
    def __str__(self):
        print("Area: ", self.A)
        print("Mod. Elasticidad: ", self.E)
        print("Coordenadas Iniciales: ({} , {})".format(self.xi, self.yi))
        print("Coordenadas Finales: ({} , {})".format(self.xf, self.yf))
        print("Vector de Cooredenadas: ", self.vc)
        print("Longitud: ", self.L)
        print("Rigidez Local:", self.k_loc)
        print("Lx = ", self.lx,"  Ly = ", self.ly )
        print("Matriz de Transformacion: ", self.T)
        print("")
        print("Rigidez global del elemento:", self.k_glob)
        return ""
    
    def Longitud(self):
        """Calcula la longitud del elemento."""
        return math.sqrt((self.xf-self.xi)**2 + (self.yf-self.yi)**2)
    
    def Rig_Loc(self):
        """Calcula la matriz de rigidez local del elemento."""
        return (self.A*self.E/self.L) * np.array([[1,-1],[-1,1]])
    
    def Lambda_X(self):
        """Calcula la lambda X del elemento."""
        return (self.xf-self.xi)/self.L
    
    def Lambda_Y(self):
        """Calcula la lambda Y del elemento."""
        return (self.yf-self.yi)/self.L
    
    def Trans(self):
        """Calcula la matriz de tarnsformación del elemento."""
        return np.array([[self.lx, self.ly, 0, 0],[0, 0, self.lx, self.ly]])
    
    def Rig_Glob(self):
        """Calcula la matriz de rigidez global del elemento."""
        Tt = np.transpose(self.T)
        Tt_k_loc = np.matmul(Tt,self.k_loc)
        return np.matmul(Tt_k_loc,self.T)
        
        

## EJEMPLO.

<img src="Img/ejemplo.png">

In [13]:
A = 2 # m2
E = 1800 # kgf/m2
xi = 0 # m
yi = 0 # m
xf = 5 # m
yf = 7 # m
vc = [1, 2, 3, 4]

Elem_1 = MiembroArmadura("Elem 1", A, E, xi, yi, xf, yf, vc)
print(Elem_1)

Area:  2
Mod. Elasticidad:  1800
Coordenadas Iniciales: (0 , 0)
Coordenadas Finales: (5 , 7)
Vector de Cooredenadas:  [1, 2, 3, 4]
Longitud:  8.602325267042627
Rigidez Local: [[ 418.49149948 -418.49149948]
 [-418.49149948  418.49149948]]
Lx =  0.5812381937190965   Ly =  0.813733471206735
Matriz de Transformacion:  [[0.58123819 0.81373347 0.         0.        ]
 [0.         0.         0.58123819 0.81373347]]

Rigidez global del elemento: [[ 141.38226334  197.93516867 -141.38226334 -197.93516867]
 [ 197.93516867  277.10923614 -197.93516867 -277.10923614]
 [-141.38226334 -197.93516867  141.38226334  197.93516867]
 [-197.93516867 -277.10923614  197.93516867  277.10923614]]

